version: 0.2
env:
  variables:
    S3_BUCKET: $ENVIRONMENT.S3_BUCKET
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo $S3_BUCKET
      - aws s3 sync --delete ./dist $S3_BUCKET